### ISSUE TITLE
Can't pull transactions from multiple accounts

### ISSUE THREAD

**Issue by wongio** [twang2218/node-cba-netbank#3]
For some reason when calling getTransactions twice it fails to download and parse the transactions in the first request. I get the error "Cannot find transaction section". When it's called on its own it works perfectly fine.

Ultimately what I want to be able to to do is: 
for ( var i = 0; i < accounts.length; i++ ){
  netbank.getTransactions(accounts[i]), callback);
}

Any ideas?

netbank.getTransactions(accounts[0], function (error, transactions) {
       if (error === null) {

```
     console.log(transactions);
   } else {
     console.error(error);
   }
 });
  netbank.getTransactions(accounts[1], function (error, transactions) {
   if (error === null) {

     console.log(transactions);
   } else {
     console.error(error);
   }
 });
```

**Comment by wongio** [comment]
I realise this may be due to the asynchronous nature of javascript. Is there a way it can be designed to scraping transactions from multiple accounts?

**Comment by wongio** [comment]
This is what I had to do to make it work.

I had to modify the api.js to support it.

var index = 0;
netbank.login(credential, function (error, accounts) {

 if (error === null) {
  //console.log(accounts);
   // Assume we are going to retrieve the transactions of the first account
        netbank.getTransactions(accounts, index, transactionsCallback);

} else {
 console.error(error);
}
});

function transactionsCallback (error, transactions, accounts){
   if (error === null) {
       // output the transactions to console, be aware, it might be a lot.
         console.log(transactions);
         console.log('---- Finished one account -----');
         index = index + 1;
         if ( index !== accounts.length ){
           netbank.getTransactions(accounts, index, transactionsCallback );
         }
       } else {
         console.error(error);
       }
};

**Comment by twang2218** [comment]
I think I can close this issue now, as I reimplemented the interface in Promise, and adjusted some API, now it's ok to retrieve history from multiple accounts in one session. Please have a look on `cli.js`, especially the `ui` command part.

However, I'm not sure whether it can be done in parallel, as there might be some restrictions on the server side.
