### ISSUE TITLE
Function Missing Logon

### ISSUE THREAD

**Issue by BorisStephens** [twang2218/node-cba-netbank#6]
![screen shot 2017-07-11 at 6 10 34 am](https://user-images.githubusercontent.com/152057/28037727-c3af3cf2-65ff-11e7-8188-9faaaaae187d.png)

When using the readme code, the logon function appears to not be working on the latest build.

**Comment by twang2218** [comment]
Sorry for the inconvenient, I changed the API and for got update the README. 😹 

And now, I published the `v0.8.0` with the updated API and updated README. The new example should works now.

**Comment by BorisStephens** [comment]
Thanks Tao – love your work!
