### ISSUE TITLE
Fails for certain account type

### ISSUE THREAD

**Issue by dwdickens** [twang2218/node-cba-netbank#7]
Hi, love this project!

The parseAccountList function is failing if the account list includes Commsec Shares.

Commsec Shares can appear in the account list, but do not contain any balance information and just functions as a convenient way to click onto your commsec portfolio on the commsec website.

This line is failing: type: `${/ACCOUNT_PRODUCT_TYPE=(\w+)/.exec(acc.link)[1]}`
TypeError: Cannot read property '1' of null

As an example of the data for this type of account, 
acc.link = "/netbank/usermaintenance/CommSecLauncher.aspx?XXXXXXXXETC,ETC"
acc.name="CommSec Shares"

I think it would be best to filter and not include this account type in the accountRows.each function - doesn't seem any point including it since no information is provided on the account screen (not even the balance).

The code below fixes the problem - you may want a more elegant way though?

if ($$('.NicknameField .left a').text().trim() != "CommSec Shares")
{
      accounts.push({
        name: $$('.NicknameField .left a').text().trim(),
        link: $$('.NicknameField .left a').attr('href'),
        bsb: $$('.BSBField .text').text().replace(/\s+/g, '').trim(),
        account: $$('.AccountNumberField .text').text().replace(/\s+/g, '').trim(),
        balance: parseCurrencyHtml($$('.AccountBalanceField')),
        available: parseCurrencyHtml($$('.AvailableFundsField'))
});

**Comment by twang2218** [comment]
Thank you for reporting the issue. I used your example and reached the same error `TypeError: Cannot read property '1' of null`, and you are right, the CommSec account should be ignored, there is no point to be included in the final account list.

And to avoid such parsing problem in the future, I wrapped the parser code in a `try{...}catch(){...}` block now, so such exception will cause the account to be ignored now. https://github.com/twang2218/node-cba-netbank/commit/84d86536887c6f8aad15b2b4177c4b4cad513cc5

I update the code and released an update `0.8.1` to address this issue, could you have a look to see whether this version fixed your issue? Thanks. :)

**Comment by dwdickens** [comment]
Great! Problem fixed :)... but another issue which I will open seperately

**Comment by twang2218** [comment]
Great, then I will close this issue now. 😸
